- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops"
    TRAINER: "anand"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, trainer is {{ TRAINER }}"  