- name: to use prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: enter user name
    private: false
  - name: password
    prompt: enter password
    private: true
  tasks:
  - name: print the username and password
    ansible.builtin.debug:
      msg: "username {{ username }}, password {{ password }}"    