- name: ansible command vs shell module
  hosts: local
  connection: local
  tasks:
  - name: command module
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output
  - name: to print the users_output
    ansible.builtin.debug:
      msg: "{{ users_output }}"